name: pocketbase

# docker network create web
networks:
  default:
    name: web
    external: true

services:

  pocketbase:
    build:
      context: ./
    restart: unless-stopped
    container_name: pocketbase
    deploy:
      resources:
        reservations:
          cpus: 0.1
          memory: 1G
        limits:
          cpus: 0.8
          memory: 4G
    ports:
      - "8090:8090"
    environment:
      DENO_ENV: production
      S3_BUCKET: ${S3_BUCKET}
      S3_REGION: ${S3_REGION}
      S3_ENDPOINT: ${S3_ENDPOINT}
      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
      S3_SECRET_KEY: ${S3_SECRET_KEY}
      SMTP_ADMIN_EMAIL: ${SMTP_ADMIN_EMAIL}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASS: ${SMTP_PASS}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_SENDER_NAME: ${SMTP_SENDER_NAME}
    volumes:
      - ./jobs:/app/jobs
      - ../common:/app/common
      - ./pb_data:/app/pb_data
      - ./pb_hooks:/app/pb_hooks
      - ./pb_migrations:/app/pb_migrations
      - ./pb_public:/app/pb_public
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://0.0.0.0:8090/api/health"]
      interval: 30s
      timeout: 5s
      retries: 3
