name: nodered

services:

  nodered:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: nodered
    deploy:
      resources:
        limits:
          cpus: 0.5
          memory: 1G
    ports:
      - "1880:1880"
    environment:
      - TZ=Europe/Paris
      - NODERED_USERNAME=${NODERED_USERNAME}
      - NODERED_PASSWORD_HASH=${NODERED_PASSWORD_HASH}
      - PB_ADMIN_USERNAME=${PB_ADMIN_USERNAME}
      - PB_ADMIN_PASSWORD=${PB_ADMIN_PASSWORD}
      - S3_BUCKET=${S3_BUCKET}
      - S3_REGION=${S3_REGION}
      - S3_ENDPOINT=${S3_ENDPOINT}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_SECRET_KEY=${S3_SECRET_KEY}
    volumes:
      - ./data:/data
      - ./settings.js:/data/settings.js
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://0.0.0.0:1880"]
      interval: 30s
      timeout: 5s
      retries: 3

networks:
  default:
    name: web
    external: true